#!/usr/bin/env ruby
require 'open3'
require 'optparse'
require 'tmpdir'
require 'fileutils'
require 'shellwords'
require 'byebug' if ENV['DEBUG']

options = {
  formats: ['raf', 'nef', 'cr2'],
}

opts = OptionParser.new do |opts|
  opts.banner = "Usage: raw2jpg [options] [directories]"

  opts.on("-e", "--extensions [FORMATS]", Array, "Extensions to search, comma seperated (default 'raf,nef,cr2')") do |value|
    options[:formats] = value
  end
  opts.on("-v", "--[no-]verbose", "Run verbosely") do |value|
    options[:verbose] = value
  end
  opts.on("-c", "--[no-]cra", "Overwrite jpgs when raw file has Camera Raw adjustments") do |value|
    options[:cra] = value
  end
  opts.on("-f", "--force", "Overwrite existing jpgs") do |value|
    options[:force] = value
  end
  opts.on("-h", "--help", "Prints this help") do
    puts opts
    exit
  end
end.parse!

class Step
  def initialize(input, output = nil)
    @input = input
    @output = output
  end
end

class ConvertWithCRA < Step
  def do
    puts "converting to DNG with Camera Raw Adjustments"
    out, _ = Open3.capture2("/Applications/Adobe DNG Converter.app/Contents/MacOS/Adobe DNG Converter",
                            '--args',
                            '-p2',
                            "-d #{@output}",
                            @input)
    out
  end
end

class ConvertExifTool < Step
  def do
    out = ''
    orientation, _ = Open3.capture2("exiftool -Orientation# \"#{@input}\"")
    out << orientation
    orientation.gsub!(/^.*: /, '').gsub!("\n", '')
    convert, _ = Open3.capture2("exiftool -b -JpgFromRaw \"#{@input}\" > \"#{@output}\"")
    out << convert
    write_orientation, _ = Open3.capture2("exiftool -Orientation#=\"#{orientation}\" \"#{@output}\" -overwrite_original_in_place")
    out << write_orientation
    out
  end
end

class ConvertSips < Step
  def do
    out, _ = Open3.capture2("sips -s format jpeg \"#{@input}\" --out \"#{@output}\"")
    out
  end
end

class CleanupDNG < Step
  def do
    FileUtils.rm(@input)
  end
end

class Processor
  attr_accessor :file

  def initialize(file, options)
    @file = file
    @options = options
  end

  def should_process?
    return true if @options[:cra] and has_cra?
    return true if File.exist?(output) and @options[:force]
    return false if File.exist?(output)
    true
  end

  def process
    steps = []
    if has_cra?
      steps << ConvertWithCRA.new(@file , Shellwords.escape(File.dirname(base)))
      steps << ConvertExifTool.new("#{base}.dng", "#{base}.jpg")
      steps << CleanupDNG.new("#{base}.dng")
    else
      steps << ConvertSips.new(@file, "#{base}.jpg")
    end

    steps.each do |step|
      out = step.do
      puts out if @options[:verbose]
    end
  end

  def output
    @output ||= "#{base}.jpg"
  end

  def has_cra?
    fname = "#{base}.xmp"
    @has_cra ||= begin
      return false unless File.exist?(fname)
      File.read(fname).include?('crs:ProcessVersion')
    end
  end

  def base
    @base ||= @file.gsub(File.extname(@file), '')
  end
end

if ARGV.empty?
  puts opts.options.help
  exit
end

dirs = ARGV.first.split(',')
puts "Finding raw files..."
files = dirs.map do |dir|
  glob = "/**/*.{#{options[:formats].join(',')}}"
  files = Dir.glob(File.join(dir, glob), File::FNM_CASEFOLD)

  files.map! do |file|
    Processor.new(file, options)
  end.select! do |p|
    p.should_process?
  end
  files
end.flatten!

if files.empty?
  puts "No files found."
  exit
end

total = files.size
puts "#{total} files to process"
files.each_with_index do |processor, i|
  count = i + 1
  puts "#{' ' * (total.to_s.size - count.to_s.size)}#{count}/#{total} converting #{processor.file}"
  processor.process
end
